//
//  StringsXmlBase.m
//
//  Created by 9vs  on 15/1/31
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import "StringsXmlBase.h"


NSString *const kStringsXmlBaseNotnetworkerror = @"notnetworkerror";
NSString *const kStringsXmlBaseLayouttitle = @"layouttitle";
NSString *const kStringsXmlBaseAppname = @"appname";
NSString *const kStringsXmlBaseAppSecret = @"AppSecret";
NSString *const kStringsXmlBaseIpaddress = @"ipaddress";
NSString *const kStringsXmlBaseRadiofirst = @"radiofirst";
NSString *const kStringsXmlBaseCancel = @"cancel";
NSString *const kStringsXmlBaseHideTop = @"HideTop";
NSString *const kStringsXmlBaseProducescount = @"producescount";
NSString *const kStringsXmlBaseTabbarTextColor = @"tabbarTextColor";
NSString *const kStringsXmlBaseIsnewversion = @"isnewversion";
NSString *const kStringsXmlBaseSubmit = @"submit";
NSString *const kStringsXmlBaseAppKey = @"AppKey";
NSString *const kStringsXmlBaseGTAppSecret = @"GTAppSecret";
NSString *const kStringsXmlBaseAppID = @"AppID";
NSString *const kStringsXmlBaseCorporateculture = @"corporateculture";
NSString *const kStringsXmlBaseBuffernotice = @"buffernotice";
NSString *const kStringsXmlBaseTwoexit = @"twoexit";
NSString *const kStringsXmlBasePushmsgipaddress = @"pushmsgipaddress";
NSString *const kStringsXmlBaseLaderoration = @"laderoration";
NSString *const kStringsXmlBaseIsScan = @"isScan";
NSString *const kStringsXmlBaseGTAppKey = @"GTAppKey";
NSString *const kStringsXmlBaseRadiomore = @"radiomore";
NSString *const kStringsXmlBaseRadioabout = @"radioabout";
NSString *const kStringsXmlBaseLayoutbody = @"layoutbody";
NSString *const kStringsXmlBaseNetworkbad = @"networkbad";
NSString *const kStringsXmlBaseNotnetworkconnected = @"notnetworkconnected";
NSString *const kStringsXmlBasePhoneipaddress = @"phoneipaddress";
NSString *const kStringsXmlBaseGTAppId = @"GTAppId";
NSString *const kStringsXmlBaseRadionews = @"radionews";
NSString *const kStringsXmlBaseBanquaninfo = @"banquaninfo";
NSString *const kStringsXmlBaseRadioproduce = @"radioproduce";
NSString *const kStringsXmlBaseNewscount = @"newscount";
NSString *const kStringsXmlBaseServeripaddress = @"serveripaddress";
NSString *const kStringsXmlBaseNotnetworkenabled = @"notnetworkenabled";
NSString *const kStringsXmlBaseAppsid = @"appsid";

NSString *const kStringsXmlBaseLoaderImageType = @"LoaderImageType";
NSString *const kStringsXmlBaseRefresImageType = @"RefresImageType";
NSString *const kStringsXmlBaseTitleBarIsShow = @"TitleBarIsShow";
NSString *const kStringsXmlBaseRightMenuIsShow = @"RightMenuIsShow";
NSString *const kStringsXmlBaseBottomMenuBarHeight = @"BottomMenuBarHeight";
NSString *const kStringsXmlBaseTitleBarHeight = @"TitleBarHeight";
NSString *const kStringsXmlBaseRightMenuFontColor = @"RightMenuFontColor";
NSString *const kStringsXmlBaseFrontSliderState = @"FrontSliderState";
NSString *const kStringsXmlBaseFrontSliderImageCount = @"FrontSliderImageCount";
NSString *const kStringXmlBaseBottomMenuBarBackColor = @"BottomMenuBarBackColor";
NSString *const kqqqaaqqqqAdaptIOS7Nav = @"adaptIOS7Nav";

NSString *const kStringsXmlBaseGPSPostInterval = @"GPSPostInterval";
NSString *const kStringsXmlBaseGPSGrabInterval = @"GPSGrabInterval";
NSString *const kStringsXmlBaseGpsPostUrl = @"GpsPostUrl";
NSString *const kStringsXmlBaseGPSIOSAppKey = @"GPSIOSAppKey";

NSString *const kStringsXmlBaseTitleBarColor = @"TitleBarColor";
NSString *const kStringsXmlBaseBMenubarTextcolorNomal = @"BMenubarTextcolorNomal";
NSString *const kStringsXmlBaseBMenubarTextcolorActive = @"BMenubarTextcolorActive";
NSString *const kStringsXmlBaseMenuBarLineColor = @"MenuBarLineColor";
NSString *const kStringsXmlBaseReturn_url = @"return_url";
NSString *const kStringsXmlBasenotify_url = @"notify_url";
NSString *const kStringsXmlBaseUMAppkey = @"UMAppkey";
NSString *const kStringsXmlBasepartner = @"PARTNER";
NSString *const kStringsXmlBaseseller = @"SELLER";
NSString *const kStringsXmlBaseRSA_PRIVATE = @"RSA_PRIVATE";
NSString *const kStringsXmlBaseRSA_PUBLIC = @"RSA_PUBLIC";
NSString *const kStringsXmlBaseIsLandscape = @"IsLandscape";
NSString *const kStringsXmlBaseWX_APP_ID = @"WX_APP_ID";
NSString *const kStringsXmlBaseWX_MCH_ID = @"WX_MCH_ID";
NSString *const kStringsXmlBaseWX_API_KEY = @"WX_API_KEY";
NSString *const kStringsXmlBaseWX_return_url = @"WX_return_url";
NSString *const kStringsXmlBaseWX_notify_url = @"WX_notify_url";
NSString *const kStringsXmlBaseWX_secrect = @"WX_SECRET";
NSString *const kStringsXmlBaseIsUnicom = @"IsUnicom";
NSString *const kStringsXmlBaseIsCloseRefres = @"IsCloseRefresh";
NSString *const kStringsXmlBaseIsCloseLoad = @"IsCloseLoad";
NSString *const kStringsXmlBaseIsClosePhoneState = @"IsClosePhoneState";
NSString *const kStringsXmlBaseYDBxmlversion = @"YDBxmlversion";
NSString *const kStringsXmlBaseYDBsvnversion = @"YDBsvnversion";
NSString *const kStringsXmlBaseQQAPPID = @"QQAPPID";
NSString *const kStringsXmlBaseiosUmengAppkey = @"IOSPushAppkey";

NSString *const kStringsXmlBasePreloadstate = @"PreloadState";
NSString *const kStringsXmlBasePreloadTime = @"PreloadTime";
NSString *const kStringsXmlBasePreloadpercent = @"PreloadPercent";
NSString *const kStringsXmlBaseRemindState = @"RemindState";
NSString *const kStringsXmlBaseRemindTime = @"RemindTime";
NSString *const kStringsXmlBaseRemindPercent= @"RemindPercent";

NSString *const kStringsXmlBaseProgressViewColor = @"ProgressViewColor";
NSString *const kStringsXmlBaseIsShowProgressView = @"IsShowProgressView";
NSString *const kStringsXmlBasePreloadImg = @"PreloadImg";
NSString *const kStringsXmlBaserongyunAppkey = @"RONG_CLOUD_APP_KEY";
NSString *const kStringsXmlOldVersionWebView = @"OldVersionWebView";
NSString *const kStringsXmlVersionName = @"versionname";
NSString *const kStringsXmlUserAgentType = @"UserAgentType";
NSString *const kStringsXmlUserAgentContent = @"UserAgentContent";
NSString *const kStringsXmlWeChatJsPath = @"WeChatJsPath";
NSString *const kStringsXmlWeChatAccessUrl = @"WeChatAccessUrl";
NSString *const kStringsXmlwebviewbg = @"webviewbg";
NSString *const kStringsXmlIsCopy = @"IsCopy";
NSString *const kStringsXmlStatusbarBgColor = @"StatusbarBgColor";
NSString *const kstringsXmlPigWxToken = @"PigWxToken";
NSString *const kstringsXmlCmsSystem = @"CmsSystem";
NSString *const kstringsXmlIsRefreshMenu = @"IsRefreshMenu";
NSString *const kstringsXmlTaobaoJs = @"TaobaoJs";
NSString *const kstringsXmlisBecomeActive = @"isBecomeActive";
NSString *const kstringsXmlAddJspath = @"AddJspath";
NSString *const kstringsWFTWXAPPID = @"WFT_WX_APP_ID";
NSString *const kstringsWFTWXMCH = @"WFT_WX_MCH";
NSString *const kstringsWFTWXSIGNKEY = @"WFT_WX_SIGNKEY";
NSString *const kstringsWFTWXNOTIFYURL = @"WFT_WX_NOTIFYURL";
NSString *const kstringsWFTWXRETURNURL = @"WFT_WX_RETURNURL";
NSString *const kstringsbcAppID = @"bcAppID";
NSString *const kstringsbcAPPSecret = @"bcAPPSecret";
NSString *const kstringsbcwxAppID = @"wxAppID";
NSString *const kstringOpenBMKmap = @"OpenBMKmap";
NSString *const kstringTranslucentBackground =@"TranslucentBackground";
NSString *const kstringiOSOriginalStyle = @"iOSOriginalStyle";
NSString *const kstringHomePage = @"HomePage";
NSString *const kstringpingtai = @"pingtai";
NSString *const kstringLogoColor = @"LogoColor";
NSString *const kstringEnableCopy = @"EnableCopy";
NSString *const kstringisShowPagecontrol = @"isShowPagecontrol";
@interface StringsXmlBase ()

- (id)objectOrNilForKey:(id)aKey fromDictionary:(NSDictionary *)dict;

@end

@implementation StringsXmlBase

@synthesize notnetworkerror = _notnetworkerror;
@synthesize layouttitle = _layouttitle;
@synthesize appname = _appname;
@synthesize appSecret = _appSecret;
@synthesize ipaddress = _ipaddress;
@synthesize radiofirst = _radiofirst;
@synthesize cancel = _cancel;
@synthesize hideTop = _hideTop;
@synthesize producescount = _producescount;
@synthesize tabbarTextColor = _tabbarTextColor;
@synthesize isnewversion = _isnewversion;
@synthesize submit = _submit;
@synthesize appKey = _appKey;
@synthesize gTAppSecret = _gTAppSecret;
@synthesize appID = _appID;
@synthesize corporateculture = _corporateculture;
@synthesize buffernotice = _buffernotice;
@synthesize twoexit = _twoexit;
@synthesize pushmsgipaddress = _pushmsgipaddress;
@synthesize laderoration = _laderoration;
@synthesize isScan = _isScan;
@synthesize gTAppKey = _gTAppKey;
@synthesize radiomore = _radiomore;
@synthesize radioabout = _radioabout;
@synthesize layoutbody = _layoutbody;
@synthesize networkbad = _networkbad;
@synthesize notnetworkconnected = _notnetworkconnected;
@synthesize phoneipaddress = _phoneipaddress;
@synthesize gTAppId = _gTAppId;
@synthesize radionews = _radionews;
@synthesize banquaninfo = _banquaninfo;
@synthesize radioproduce = _radioproduce;
@synthesize newscount = _newscount;
@synthesize serveripaddress = _serveripaddress;
@synthesize notnetworkenabled = _notnetworkenabled;
@synthesize appsid = _appsid;
@synthesize rightMenuFontColor = _rightMenuFontColor;
@synthesize refresImageType = _refresImageType;
@synthesize titleBarIsShow = _titleBarIsShow;
@synthesize rightMenuIsShow = _rightMenuIsShow;
@synthesize frontSliderState = _frontSliderState;
@synthesize titleBarHeight = _titleBarHeight;
@synthesize frontSliderImageCount = _frontSliderImageCount;
@synthesize bottomMenuBarHeight = _bottomMenuBarHeight;
@synthesize loaderImageType = _loaderImageType;
@synthesize return_url = _return_url;
@synthesize notify_url = _notify_url;
@synthesize umappkey = _umappkey;
@synthesize partner = _partner;
@synthesize seller = _seller;
@synthesize rsa_private = _rsa_private;
@synthesize rsa_public = _rsa_public;
@synthesize isLandscape = _isLandscape;
@synthesize wxappid = _wxappid;
@synthesize wxmchid = _wxmchid;
@synthesize wxapikey = _wxapikey;
@synthesize wxreturnurl = _wxreturnurl;
@synthesize wxnotifyurl = _wxnotifyurl;
@synthesize wxsecrect = _wxsecrect;
@synthesize isUnicom = _isUnicom;
@synthesize isCloseRefresh = _isCloseRefresh;
@synthesize isCloseLoad = _isCloseLoad;
@synthesize isClosePhoneState = _isClosePhoneState;
@synthesize ydbSvnversion = _ydbSvnversion;
@synthesize ydbXmlversion = _ydbXmlversion;
@synthesize qqappid = _qqappid;
@synthesize iosUmengAppkey = _iosUmengAppkey;
@synthesize PreloadState = _PreloadState;
@synthesize PreloadPercent = _PreloadPercent;
@synthesize PreloadTime = _PreloadTime;
@synthesize RemindState = _RemindState;
@synthesize RemindPercent = _RemindPercent;
@synthesize RemindTime = _RemindTime;
@synthesize IsShowProgressView = _IsShowProgressView;
@synthesize ProgressViewColor = _ProgressViewColor;
@synthesize PreloadImg = _PreloadImg;
@synthesize RongyonAppkey = _RongyonAppkey;
@synthesize oldVersionWebView = _oldVersionWebView;
@synthesize UserAgentType = _UserAgentType;
@synthesize UserAgentContent = _UserAgentContent;
@synthesize WeChatJsPath = _WeChatJsPath;
@synthesize WeChatAccessUrl = _WeChatAccessUrl;
@synthesize webviewbg = _webviewbg;
@synthesize IsCopy = _IsCopy;
@synthesize statusbarBgColor = _statusbarBgColor;
@synthesize PigWxToken = _PigWxToken;
@synthesize CmsSystem = _CmsSystem;
@synthesize IsRefreshMenu = _IsRefreshMenu;
@synthesize TaobaoJs = _TaobaoJs;
@synthesize isBecomeActive = _isBecomeActive;
@synthesize AddJspath = _AddJspath;
@synthesize WFTWXMCH = _WFTWXMCH;
@synthesize WFTWXAPPID = _WFTWXAPPID;
@synthesize WFTWXSIGNKEY = _WFTWXSIGNKEY;
@synthesize WFTWXNOTIFYURL = _WFTWXNOTIFYURL;
@synthesize WFTWXRETURNURL = _WFTWXRETURNURL;
@synthesize bcAppID = _bcAppID;
@synthesize bcAPPSecret = _bcAPPSecret;
@synthesize bcwxAppID = _bcwxAppID;
@synthesize OpenBMKmap =_OpenBMKmap;
@synthesize TranslucentBackground = _TranslucentBackground;
@synthesize iOSOriginalStyle = _iOSOriginalStyle;
@synthesize HomePage = _HomePage;
@synthesize pingtai = _pingtai;
@synthesize LogoColor = _LogoColor;
@synthesize EnableCopy = _EnableCopy;
@synthesize isShowPagecontrol = _isShowPagecontrol;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dict
{
    return [[self alloc] initWithDictionary:dict];
}

- (instancetype)initWithDictionary:(NSDictionary *)dict
{
    self = [super init];
    
    // This check serves to make sure that a non-NSDictionary object
    // passed into the model class doesn't break the parsing.
    if(self && [dict isKindOfClass:[NSDictionary class]]) {
        self.notnetworkerror = [self objectOrNilForKey:kStringsXmlBaseNotnetworkerror fromDictionary:dict];
        self.layouttitle = [self objectOrNilForKey:kStringsXmlBaseLayouttitle fromDictionary:dict];
        self.appname = [self objectOrNilForKey:kStringsXmlBaseAppname fromDictionary:dict];
        self.appSecret = [self objectOrNilForKey:kStringsXmlBaseAppSecret fromDictionary:dict];
        self.ipaddress = [self objectOrNilForKey:kStringsXmlBaseIpaddress fromDictionary:dict];
        self.radiofirst = [self objectOrNilForKey:kStringsXmlBaseRadiofirst fromDictionary:dict];
        self.cancel = [self objectOrNilForKey:kStringsXmlBaseCancel fromDictionary:dict];
        self.hideTop = [self objectOrNilForKey:kStringsXmlBaseHideTop fromDictionary:dict];
        self.producescount = [self objectOrNilForKey:kStringsXmlBaseProducescount fromDictionary:dict];
        self.tabbarTextColor = [self objectOrNilForKey:kStringsXmlBaseTabbarTextColor fromDictionary:dict];
        self.isnewversion = [self objectOrNilForKey:kStringsXmlBaseIsnewversion fromDictionary:dict];
        self.submit = [self objectOrNilForKey:kStringsXmlBaseSubmit fromDictionary:dict];
        self.appKey = [self objectOrNilForKey:kStringsXmlBaseAppKey fromDictionary:dict];
        self.gTAppSecret = [self objectOrNilForKey:kStringsXmlBaseGTAppSecret fromDictionary:dict];
        self.appID = [self objectOrNilForKey:kStringsXmlBaseAppID fromDictionary:dict];
        self.corporateculture = [self objectOrNilForKey:kStringsXmlBaseCorporateculture fromDictionary:dict];
        self.buffernotice = [self objectOrNilForKey:kStringsXmlBaseBuffernotice fromDictionary:dict];
        self.twoexit = [self objectOrNilForKey:kStringsXmlBaseTwoexit fromDictionary:dict];
        self.pushmsgipaddress = [self objectOrNilForKey:kStringsXmlBasePushmsgipaddress fromDictionary:dict];
        self.laderoration = [self objectOrNilForKey:kStringsXmlBaseLaderoration fromDictionary:dict];
        self.isScan = [self objectOrNilForKey:kStringsXmlBaseIsScan fromDictionary:dict];
        self.gTAppKey = [self objectOrNilForKey:kStringsXmlBaseGTAppKey fromDictionary:dict];
        self.radiomore = [self objectOrNilForKey:kStringsXmlBaseRadiomore fromDictionary:dict];
        self.radioabout = [self objectOrNilForKey:kStringsXmlBaseRadioabout fromDictionary:dict];
        self.layoutbody = [self objectOrNilForKey:kStringsXmlBaseLayoutbody fromDictionary:dict];
        self.networkbad = [self objectOrNilForKey:kStringsXmlBaseNetworkbad fromDictionary:dict];
        self.notnetworkconnected = [self objectOrNilForKey:kStringsXmlBaseNotnetworkconnected fromDictionary:dict];
        self.phoneipaddress = [self objectOrNilForKey:kStringsXmlBasePhoneipaddress fromDictionary:dict];
        self.gTAppId = [self objectOrNilForKey:kStringsXmlBaseGTAppId fromDictionary:dict];
        self.radionews = [self objectOrNilForKey:kStringsXmlBaseRadionews fromDictionary:dict];
        self.banquaninfo = [self objectOrNilForKey:kStringsXmlBaseBanquaninfo fromDictionary:dict];
        self.radioproduce = [self objectOrNilForKey:kStringsXmlBaseRadioproduce fromDictionary:dict];
        self.newscount = [self objectOrNilForKey:kStringsXmlBaseNewscount fromDictionary:dict];
        self.serveripaddress = [self objectOrNilForKey:kStringsXmlBaseServeripaddress fromDictionary:dict];
        self.notnetworkenabled = [self objectOrNilForKey:kStringsXmlBaseNotnetworkenabled fromDictionary:dict];
        self.appsid = [self objectOrNilForKey:kStringsXmlBaseAppsid fromDictionary:dict];
        
        self.loaderImageType = [self objectOrNilForKey:kStringsXmlBaseLoaderImageType fromDictionary:dict];
        self.refresImageType = [self objectOrNilForKey:kStringsXmlBaseRefresImageType fromDictionary:dict];
        self.titleBarIsShow = [self objectOrNilForKey:kStringsXmlBaseTitleBarIsShow fromDictionary:dict];
        self.rightMenuIsShow = [self objectOrNilForKey:kStringsXmlBaseRightMenuIsShow fromDictionary:dict];
        self.bottomMenuBarHeight = [self objectOrNilForKey:kStringsXmlBaseBottomMenuBarHeight fromDictionary:dict];
        self.titleBarHeight = [self objectOrNilForKey:kStringsXmlBaseTitleBarHeight fromDictionary:dict];
        self.rightMenuFontColor = [self objectOrNilForKey:kStringsXmlBaseRightMenuFontColor fromDictionary:dict];
        self.frontSliderState = [self objectOrNilForKey:kStringsXmlBaseFrontSliderState fromDictionary:dict];
        self.frontSliderImageCount = [self objectOrNilForKey:kStringsXmlBaseFrontSliderImageCount fromDictionary:dict];
        self.bottomMenuBarBackColor = [self objectOrNilForKey:kStringXmlBaseBottomMenuBarBackColor fromDictionary:dict];
        self.adaptIOS7Nav = [self objectOrNilForKey:kqqqaaqqqqAdaptIOS7Nav fromDictionary:dict];
        
        self.gPSPostInterval = [self objectOrNilForKey:kStringsXmlBaseGPSPostInterval fromDictionary:dict];
        self.gPSGrabInterval = [self objectOrNilForKey:kStringsXmlBaseGPSGrabInterval fromDictionary:dict];
        self.gpsPostUrl = [self objectOrNilForKey:kStringsXmlBaseGpsPostUrl fromDictionary:dict];
        self.gPSIOSAppKey = [self objectOrNilForKey:kStringsXmlBaseGPSIOSAppKey fromDictionary:dict];
        self.titleBarColor = [self objectOrNilForKey:kStringsXmlBaseTitleBarColor fromDictionary:dict];
        self.bMenubarTextcolorNomal = [self objectOrNilForKey:kStringsXmlBaseBMenubarTextcolorNomal fromDictionary:dict];
        self.bMenubarTextcolorActive = [self objectOrNilForKey:kStringsXmlBaseBMenubarTextcolorActive fromDictionary:dict];
        self.menuBarLineColor = [self objectOrNilForKey:kStringsXmlBaseMenuBarLineColor fromDictionary:dict];
        self.return_url = [self objectOrNilForKey:kStringsXmlBaseReturn_url fromDictionary:dict];
        self.notify_url = [self objectOrNilForKey:kStringsXmlBasenotify_url fromDictionary:dict];
        self.umappkey = [self objectOrNilForKey:kStringsXmlBaseUMAppkey fromDictionary:dict];
        self.partner = [self objectOrNilForKey:kStringsXmlBasepartner fromDictionary:dict];
        self.seller = [self objectOrNilForKey:kStringsXmlBaseseller fromDictionary:dict];
        self.rsa_private = [self objectOrNilForKey:kStringsXmlBaseRSA_PRIVATE fromDictionary:dict];
        self.rsa_public = [self objectOrNilForKey:kStringsXmlBaseRSA_PUBLIC fromDictionary:dict];
        self.isLandscape = [self objectOrNilForKey:kStringsXmlBaseIsLandscape fromDictionary:dict];
        self.wxappid = [self objectOrNilForKey:kStringsXmlBaseWX_APP_ID fromDictionary:dict];
        self.wxmchid = [self objectOrNilForKey:kStringsXmlBaseWX_MCH_ID fromDictionary:dict];
        self.wxapikey = [self objectOrNilForKey:kStringsXmlBaseWX_API_KEY fromDictionary:dict];
        self.wxnotifyurl = [self objectOrNilForKey:kStringsXmlBaseWX_notify_url fromDictionary:dict];
        self.wxreturnurl = [self objectOrNilForKey:kStringsXmlBaseWX_return_url fromDictionary:dict];
        self.wxsecrect = [self objectOrNilForKey:kStringsXmlBaseWX_secrect fromDictionary:dict];
        self.isUnicom = [self objectOrNilForKey:kStringsXmlBaseIsUnicom fromDictionary:dict];
        self.isCloseRefresh = [self objectOrNilForKey:kStringsXmlBaseIsCloseRefres fromDictionary:dict];
        self.isCloseLoad = [self objectOrNilForKey:kStringsXmlBaseIsCloseLoad fromDictionary:dict];
        self.isClosePhoneState = [self objectOrNilForKey:kStringsXmlBaseIsClosePhoneState fromDictionary:dict];
        self.ydbXmlversion = [self objectOrNilForKey:kStringsXmlBaseYDBxmlversion fromDictionary:dict];
        self.ydbSvnversion = [self objectOrNilForKey:kStringsXmlBaseYDBsvnversion fromDictionary:dict];
        self.qqappid = [self objectOrNilForKey:kStringsXmlBaseQQAPPID fromDictionary:dict];
        self.iosUmengAppkey = [self objectOrNilForKey:kStringsXmlBaseiosUmengAppkey fromDictionary:dict];
        self.PreloadState = [self objectOrNilForKey:kStringsXmlBasePreloadstate fromDictionary:dict];
        self.PreloadPercent = [self objectOrNilForKey:kStringsXmlBasePreloadpercent fromDictionary:dict];
        self.PreloadTime = [self objectOrNilForKey:kStringsXmlBasePreloadTime fromDictionary:dict];
        self.RemindPercent = [self objectOrNilForKey:kStringsXmlBaseRemindPercent fromDictionary:dict];
        self.RemindState = [self objectOrNilForKey:kStringsXmlBaseRemindState fromDictionary:dict];
        self.RemindTime = [self objectOrNilForKey:kStringsXmlBaseRemindTime fromDictionary:dict];
        self.ProgressViewColor = [self objectOrNilForKey:kStringsXmlBaseProgressViewColor fromDictionary:dict];
        self.IsShowProgressView = [self objectOrNilForKey:kStringsXmlBaseIsShowProgressView fromDictionary:dict];
        self.IsShowProgressView = [self objectOrNilForKey:kStringsXmlBaseIsShowProgressView fromDictionary:dict];
        self.PreloadImg = [self objectOrNilForKey:kStringsXmlBasePreloadImg fromDictionary:dict];
        self.RongyonAppkey = [self objectOrNilForKey:kStringsXmlBaserongyunAppkey fromDictionary:dict];
        self.oldVersionWebView = [self objectOrNilForKey:kStringsXmlOldVersionWebView fromDictionary:dict];
        self.versionName = [self objectOrNilForKey:kStringsXmlVersionName fromDictionary:dict];
        self.UserAgentType = [self objectOrNilForKey:kStringsXmlUserAgentType fromDictionary:dict];
        self.UserAgentContent = [self objectOrNilForKey:kStringsXmlUserAgentContent fromDictionary:dict];
        self.WeChatJsPath = [self objectOrNilForKey:kStringsXmlWeChatJsPath fromDictionary:dict];
        self.WeChatAccessUrl = [self objectOrNilForKey:kStringsXmlWeChatAccessUrl fromDictionary:dict];
        self.webviewbg = [self objectOrNilForKey:kStringsXmlwebviewbg fromDictionary:dict];
        self.IsCopy = [self objectOrNilForKey:kStringsXmlIsCopy fromDictionary:dict];
        self.statusbarBgColor = [self objectOrNilForKey:kStringsXmlStatusbarBgColor fromDictionary:dict];
        self.PigWxToken = [self objectOrNilForKey:kstringsXmlPigWxToken fromDictionary:dict];
        self.CmsSystem = [self objectOrNilForKey:kstringsXmlCmsSystem fromDictionary:dict];
        self.IsRefreshMenu = [self objectOrNilForKey:kstringsXmlIsRefreshMenu fromDictionary:dict];
        self.TaobaoJs = [self objectOrNilForKey:kstringsXmlTaobaoJs fromDictionary:dict];
        self.isBecomeActive = [self objectOrNilForKey:kstringsXmlisBecomeActive fromDictionary:dict];
        self.AddJspath = [self objectOrNilForKey:kstringsXmlAddJspath fromDictionary:dict];
        self.WFTWXAPPID = [self objectOrNilForKey:kstringsWFTWXAPPID fromDictionary:dict];
        self.WFTWXMCH = [self objectOrNilForKey:kstringsWFTWXMCH fromDictionary:dict];
        self.WFTWXRETURNURL = [self objectOrNilForKey:kstringsWFTWXRETURNURL fromDictionary:dict];
        self.WFTWXNOTIFYURL = [self objectOrNilForKey:kstringsWFTWXNOTIFYURL fromDictionary:dict];
        self.WFTWXSIGNKEY = [self objectOrNilForKey:kstringsWFTWXSIGNKEY fromDictionary:dict];
        self.bcwxAppID = [self objectOrNilForKey:kstringsbcwxAppID fromDictionary:dict];
        self.bcAPPSecret = [self objectOrNilForKey:kstringsbcAPPSecret fromDictionary:dict];
        self.bcAppID = [self objectOrNilForKey:kstringsbcAppID fromDictionary:dict];
        self.OpenBMKmap = [self objectOrNilForKey:kstringOpenBMKmap fromDictionary:dict];
        self.TranslucentBackground = [self objectOrNilForKey:kstringTranslucentBackground fromDictionary:dict];
        self.iOSOriginalStyle = [self objectOrNilForKey:kstringiOSOriginalStyle fromDictionary:dict];
        self.HomePage = [self objectOrNilForKey:kstringHomePage fromDictionary:dict];
        self.pingtai = [self objectOrNilForKey:kstringpingtai fromDictionary:dict];
        self.LogoColor = [self objectOrNilForKey:kstringLogoColor fromDictionary:dict];
        self.EnableCopy = [self objectOrNilForKey:kstringEnableCopy fromDictionary:dict];
        self.isShowPagecontrol = [self objectOrNilForKey:kstringisShowPagecontrol fromDictionary:dict];
    }
    
    return self;
    
}

- (NSDictionary *)dictionaryRepresentation
{
    NSMutableDictionary *mutableDict = [NSMutableDictionary dictionary];
    [mutableDict setValue:self.notnetworkerror forKey:kStringsXmlBaseNotnetworkerror];
    [mutableDict setValue:self.layouttitle forKey:kStringsXmlBaseLayouttitle];
    [mutableDict setValue:self.appname forKey:kStringsXmlBaseAppname];
    [mutableDict setValue:self.appSecret forKey:kStringsXmlBaseAppSecret];
    [mutableDict setValue:self.ipaddress forKey:kStringsXmlBaseIpaddress];
    [mutableDict setValue:self.radiofirst forKey:kStringsXmlBaseRadiofirst];
    [mutableDict setValue:self.cancel forKey:kStringsXmlBaseCancel];
    [mutableDict setValue:self.hideTop forKey:kStringsXmlBaseHideTop];
    [mutableDict setValue:self.producescount forKey:kStringsXmlBaseProducescount];
    [mutableDict setValue:self.tabbarTextColor forKey:kStringsXmlBaseTabbarTextColor];
    [mutableDict setValue:self.isnewversion forKey:kStringsXmlBaseIsnewversion];
    [mutableDict setValue:self.submit forKey:kStringsXmlBaseSubmit];
    [mutableDict setValue:self.appKey forKey:kStringsXmlBaseAppKey];
    [mutableDict setValue:self.gTAppSecret forKey:kStringsXmlBaseGTAppSecret];
    [mutableDict setValue:self.appID forKey:kStringsXmlBaseAppID];
    [mutableDict setValue:self.corporateculture forKey:kStringsXmlBaseCorporateculture];
    [mutableDict setValue:self.buffernotice forKey:kStringsXmlBaseBuffernotice];
    [mutableDict setValue:self.twoexit forKey:kStringsXmlBaseTwoexit];
    [mutableDict setValue:self.pushmsgipaddress forKey:kStringsXmlBasePushmsgipaddress];
    [mutableDict setValue:self.laderoration forKey:kStringsXmlBaseLaderoration];
    [mutableDict setValue:self.isScan forKey:kStringsXmlBaseIsScan];
    [mutableDict setValue:self.gTAppKey forKey:kStringsXmlBaseGTAppKey];
    [mutableDict setValue:self.radiomore forKey:kStringsXmlBaseRadiomore];
    [mutableDict setValue:self.radioabout forKey:kStringsXmlBaseRadioabout];
    [mutableDict setValue:self.layoutbody forKey:kStringsXmlBaseLayoutbody];
    [mutableDict setValue:self.networkbad forKey:kStringsXmlBaseNetworkbad];
    [mutableDict setValue:self.notnetworkconnected forKey:kStringsXmlBaseNotnetworkconnected];
    [mutableDict setValue:self.phoneipaddress forKey:kStringsXmlBasePhoneipaddress];
    [mutableDict setValue:self.gTAppId forKey:kStringsXmlBaseGTAppId];
    [mutableDict setValue:self.radionews forKey:kStringsXmlBaseRadionews];
    [mutableDict setValue:self.banquaninfo forKey:kStringsXmlBaseBanquaninfo];
    [mutableDict setValue:self.radioproduce forKey:kStringsXmlBaseRadioproduce];
    [mutableDict setValue:self.newscount forKey:kStringsXmlBaseNewscount];
    [mutableDict setValue:self.serveripaddress forKey:kStringsXmlBaseServeripaddress];
    [mutableDict setValue:self.notnetworkenabled forKey:kStringsXmlBaseNotnetworkenabled];
    [mutableDict setValue:self.appsid forKey:kStringsXmlBaseAppsid];
    [mutableDict setValue:self.loaderImageType forKey:kStringsXmlBaseLoaderImageType];
    [mutableDict setValue:self.refresImageType forKey:kStringsXmlBaseRefresImageType];
    [mutableDict setValue:self.titleBarIsShow forKey:kStringsXmlBaseTitleBarIsShow];
    [mutableDict setValue:self.rightMenuIsShow forKey:kStringsXmlBaseRightMenuIsShow];
    [mutableDict setValue:self.bottomMenuBarHeight forKey:kStringsXmlBaseBottomMenuBarHeight];
    [mutableDict setValue:self.titleBarHeight forKey:kStringsXmlBaseTitleBarHeight];
    [mutableDict setValue:self.rightMenuFontColor forKey:kStringsXmlBaseRightMenuFontColor];
    [mutableDict setValue:self.frontSliderState forKey:kStringsXmlBaseFrontSliderState];
    [mutableDict setValue:self.frontSliderImageCount forKey:kStringsXmlBaseFrontSliderImageCount];
    [mutableDict setValue:self.bottomMenuBarBackColor forKey:kStringXmlBaseBottomMenuBarBackColor];
    [mutableDict setValue:self.adaptIOS7Nav forKey:kqqqaaqqqqAdaptIOS7Nav];
    
    [mutableDict setValue:self.gPSPostInterval forKey:kStringsXmlBaseGPSPostInterval];
    [mutableDict setValue:self.gPSGrabInterval forKey:kStringsXmlBaseGPSGrabInterval];
    [mutableDict setValue:self.gpsPostUrl forKey:kStringsXmlBaseGpsPostUrl];
    [mutableDict setValue:self.gPSIOSAppKey forKey:kStringsXmlBaseGPSIOSAppKey];
    [mutableDict setValue:self.titleBarColor forKey:kStringsXmlBaseTitleBarColor];
    [mutableDict setValue:self.bMenubarTextcolorNomal forKey:kStringsXmlBaseBMenubarTextcolorNomal];
    [mutableDict setValue:self.bMenubarTextcolorActive forKey:kStringsXmlBaseBMenubarTextcolorActive];
    [mutableDict setValue:self.menuBarLineColor forKey:kStringsXmlBaseMenuBarLineColor];
    [mutableDict setValue:self.return_url forKey:kStringsXmlBaseReturn_url];
    [mutableDict setValue:self.notify_url forKey:kStringsXmlBasenotify_url];
    [mutableDict setValue:self.umappkey forKey:kStringsXmlBaseUMAppkey];
    [mutableDict setObject:self.partner forKey:kStringsXmlBasepartner];
    [mutableDict setObject:self.seller forKey:kStringsXmlBaseseller];
    [mutableDict setObject:self.rsa_private forKey:kStringsXmlBaseRSA_PRIVATE];
    [mutableDict setObject:self.rsa_public forKey:kStringsXmlBaseRSA_PUBLIC];
    [mutableDict setObject:self.isLandscape forKey:kStringsXmlBaseIsLandscape];
    [mutableDict setObject:self.wxappid forKey:kStringsXmlBaseWX_APP_ID];
    [mutableDict setObject:self.wxmchid forKey:kStringsXmlBaseWX_MCH_ID];
    [mutableDict setObject:self.wxapikey forKey:kStringsXmlBaseWX_API_KEY];
    [mutableDict setObject:self.wxnotifyurl forKey:kStringsXmlBaseWX_notify_url];
    [mutableDict setObject:self.wxreturnurl forKey:kStringsXmlBaseWX_return_url];
    [mutableDict setObject:self.wxsecrect forKey:kStringsXmlBaseWX_secrect];
    [mutableDict setObject:self.isUnicom forKey:kStringsXmlBaseIsUnicom];
    [mutableDict setObject:self.isClosePhoneState forKey:kStringsXmlBaseIsClosePhoneState];
    [mutableDict setObject:self.isCloseLoad  forKey:kStringsXmlBaseIsCloseLoad];
    [mutableDict setObject:self.isCloseRefresh forKey:kStringsXmlBaseIsCloseRefres];
    [mutableDict setObject:self.ydbSvnversion forKey:kStringsXmlBaseYDBsvnversion];
    [mutableDict setObject:self.ydbXmlversion forKey:kStringsXmlBaseYDBxmlversion];
    [mutableDict setObject:self.qqappid forKey:kStringsXmlBaseQQAPPID];
    [mutableDict setObject:self.iosUmengAppkey forKey:kStringsXmlBaseiosUmengAppkey];
    [mutableDict setObject:self.PreloadState forKey:kStringsXmlBasePreloadstate];
    [mutableDict setObject:self.PreloadPercent forKey:kStringsXmlBasePreloadpercent];
    [mutableDict setObject:self.PreloadTime forKey:kStringsXmlBasePreloadTime];
    [mutableDict setObject:self.RemindTime forKey:kStringsXmlBaseRemindTime];
    [mutableDict setObject:self.RemindState forKey:kStringsXmlBaseRemindState];
    [mutableDict setObject:self.RemindPercent forKey:kStringsXmlBaseRemindPercent];
    [mutableDict setObject:self.IsShowProgressView forKey:kStringsXmlBaseIsShowProgressView];
    [mutableDict setObject:self.ProgressViewColor forKey:kStringsXmlBaseProgressViewColor];
    [mutableDict setObject:self.PreloadImg forKey:kStringsXmlBasePreloadImg];
    [mutableDict setObject:self.RongyonAppkey forKey:kStringsXmlBaserongyunAppkey];
    [mutableDict setObject:self.oldVersionWebView forKey:kStringsXmlOldVersionWebView];
    [mutableDict setObject:self.versionName forKey:kStringsXmlVersionName];
    [mutableDict setObject:self.UserAgentType forKey:kStringsXmlUserAgentType];
    [mutableDict setObject:self.UserAgentContent forKey:kStringsXmlUserAgentContent];
    [mutableDict setObject:self.WeChatJsPath forKey:kStringsXmlWeChatJsPath];
    [mutableDict setObject:self.WeChatAccessUrl forKey:kStringsXmlWeChatAccessUrl];
    [mutableDict setObject:self.webviewbg forKey:kStringsXmlwebviewbg];
    [mutableDict setObject:self.IsCopy forKey:kStringsXmlIsCopy];
    [mutableDict setObject:self.statusbarBgColor forKey:kStringsXmlStatusbarBgColor];
    [mutableDict setObject:self.PigWxToken forKey:kstringsXmlPigWxToken];
    [mutableDict setObject:self.CmsSystem forKey:kstringsXmlCmsSystem];
    [mutableDict setObject:self.IsRefreshMenu forKey:kstringsXmlIsRefreshMenu];
    [mutableDict setObject:self.TaobaoJs forKey:kstringsXmlTaobaoJs];
    [mutableDict setObject:self.isBecomeActive forKey:kstringsXmlisBecomeActive];
    [mutableDict setObject:self.AddJspath forKey:kstringsXmlAddJspath];
    [mutableDict setObject:self.WFTWXSIGNKEY forKey:kstringsWFTWXSIGNKEY];
    [mutableDict setObject:self.WFTWXNOTIFYURL forKey:kstringsWFTWXNOTIFYURL];
    [mutableDict setObject:self.WFTWXRETURNURL forKey:kstringsWFTWXRETURNURL];
    [mutableDict setObject:self.WFTWXMCH forKey:kstringsWFTWXMCH];
    [mutableDict setObject:self.WFTWXAPPID forKey:kstringsWFTWXAPPID];
    [mutableDict setObject:self.bcAppID forKey:kstringsbcAppID];
    [mutableDict setObject:self.bcAPPSecret forKey:kstringsbcAPPSecret];
    [mutableDict setObject:self.bcwxAppID forKey:kstringsbcwxAppID];
    [mutableDict setObject:self.OpenBMKmap forKey:kstringOpenBMKmap];
    [mutableDict setObject:self.TranslucentBackground forKey:kstringTranslucentBackground];
    [mutableDict setObject:self.iOSOriginalStyle forKey:kstringiOSOriginalStyle];
    [mutableDict setObject:self.HomePage forKey:kstringHomePage];
    [mutableDict setObject:self.pingtai forKey:kstringpingtai];
    [mutableDict setObject:self.LogoColor forKey:kstringLogoColor];
    [mutableDict setObject:self.EnableCopy forKey:kstringEnableCopy];
    [mutableDict setObject:self.isShowPagecontrol forKey:kstringisShowPagecontrol];
    return [NSDictionary dictionaryWithDictionary:mutableDict];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"%@", [self dictionaryRepresentation]];
}

#pragma mark - Helper Method
- (id)objectOrNilForKey:(id)aKey fromDictionary:(NSDictionary *)dict
{
    id object = [dict objectForKey:aKey];
    return [object isEqual:[NSNull null]] ? nil : object;
}


#pragma mark - NSCoding Methods

- (id)initWithCoder:(NSCoder *)aDecoder
{
    self = [super init];
    
    self.notnetworkerror = [aDecoder decodeObjectForKey:kStringsXmlBaseNotnetworkerror];
    self.layouttitle = [aDecoder decodeObjectForKey:kStringsXmlBaseLayouttitle];
    self.appname = [aDecoder decodeObjectForKey:kStringsXmlBaseAppname];
    self.appSecret = [aDecoder decodeObjectForKey:kStringsXmlBaseAppSecret];
    self.ipaddress = [aDecoder decodeObjectForKey:kStringsXmlBaseIpaddress];
    self.radiofirst = [aDecoder decodeObjectForKey:kStringsXmlBaseRadiofirst];
    self.cancel = [aDecoder decodeObjectForKey:kStringsXmlBaseCancel];
    self.hideTop = [aDecoder decodeObjectForKey:kStringsXmlBaseHideTop];
    self.producescount = [aDecoder decodeObjectForKey:kStringsXmlBaseProducescount];
    self.tabbarTextColor = [aDecoder decodeObjectForKey:kStringsXmlBaseTabbarTextColor];
    self.isnewversion = [aDecoder decodeObjectForKey:kStringsXmlBaseIsnewversion];
    self.submit = [aDecoder decodeObjectForKey:kStringsXmlBaseSubmit];
    self.appKey = [aDecoder decodeObjectForKey:kStringsXmlBaseAppKey];
    self.gTAppSecret = [aDecoder decodeObjectForKey:kStringsXmlBaseGTAppSecret];
    self.appID = [aDecoder decodeObjectForKey:kStringsXmlBaseAppID];
    self.corporateculture = [aDecoder decodeObjectForKey:kStringsXmlBaseCorporateculture];
    self.buffernotice = [aDecoder decodeObjectForKey:kStringsXmlBaseBuffernotice];
    self.twoexit = [aDecoder decodeObjectForKey:kStringsXmlBaseTwoexit];
    self.pushmsgipaddress = [aDecoder decodeObjectForKey:kStringsXmlBasePushmsgipaddress];
    self.laderoration = [aDecoder decodeObjectForKey:kStringsXmlBaseLaderoration];
    self.isScan = [aDecoder decodeObjectForKey:kStringsXmlBaseIsScan];
    self.gTAppKey = [aDecoder decodeObjectForKey:kStringsXmlBaseGTAppKey];
    self.radiomore = [aDecoder decodeObjectForKey:kStringsXmlBaseRadiomore];
    self.radioabout = [aDecoder decodeObjectForKey:kStringsXmlBaseRadioabout];
    self.layoutbody = [aDecoder decodeObjectForKey:kStringsXmlBaseLayoutbody];
    self.networkbad = [aDecoder decodeObjectForKey:kStringsXmlBaseNetworkbad];
    self.notnetworkconnected = [aDecoder decodeObjectForKey:kStringsXmlBaseNotnetworkconnected];
    self.phoneipaddress = [aDecoder decodeObjectForKey:kStringsXmlBasePhoneipaddress];
    self.gTAppId = [aDecoder decodeObjectForKey:kStringsXmlBaseGTAppId];
    self.radionews = [aDecoder decodeObjectForKey:kStringsXmlBaseRadionews];
    self.banquaninfo = [aDecoder decodeObjectForKey:kStringsXmlBaseBanquaninfo];
    self.radioproduce = [aDecoder decodeObjectForKey:kStringsXmlBaseRadioproduce];
    self.newscount = [aDecoder decodeObjectForKey:kStringsXmlBaseNewscount];
    self.serveripaddress = [aDecoder decodeObjectForKey:kStringsXmlBaseServeripaddress];
    self.notnetworkenabled = [aDecoder decodeObjectForKey:kStringsXmlBaseNotnetworkenabled];
    self.appsid = [aDecoder decodeObjectForKey:kStringsXmlBaseAppsid];
    self.loaderImageType = [aDecoder decodeObjectForKey:kStringsXmlBaseLoaderImageType];
    self.refresImageType = [aDecoder decodeObjectForKey:kStringsXmlBaseRefresImageType];
    self.titleBarIsShow = [aDecoder decodeObjectForKey:kStringsXmlBaseTitleBarIsShow];
    self.rightMenuIsShow = [aDecoder decodeObjectForKey:kStringsXmlBaseRightMenuIsShow];
    self.bottomMenuBarHeight = [aDecoder decodeObjectForKey:kStringsXmlBaseBottomMenuBarHeight];
    self.titleBarHeight = [aDecoder decodeObjectForKey:kStringsXmlBaseTitleBarHeight];
    self.rightMenuFontColor = [aDecoder decodeObjectForKey:kStringsXmlBaseRightMenuFontColor];
    self.frontSliderState = [aDecoder decodeObjectForKey:kStringsXmlBaseFrontSliderState];
    self.frontSliderImageCount = [aDecoder decodeObjectForKey:kStringsXmlBaseFrontSliderImageCount];
    self.bottomMenuBarBackColor = [aDecoder decodeObjectForKey:kStringXmlBaseBottomMenuBarBackColor];
    self.adaptIOS7Nav = [aDecoder decodeObjectForKey:kqqqaaqqqqAdaptIOS7Nav];
    self.gPSPostInterval = [aDecoder decodeObjectForKey:kStringsXmlBaseGPSPostInterval];
    self.gPSGrabInterval = [aDecoder decodeObjectForKey:kStringsXmlBaseGPSGrabInterval];
    self.gpsPostUrl = [aDecoder decodeObjectForKey:kStringsXmlBaseGpsPostUrl];
    self.gPSIOSAppKey = [aDecoder decodeObjectForKey:kStringsXmlBaseGPSIOSAppKey];
    self.titleBarColor = [aDecoder decodeObjectForKey:kStringsXmlBaseTitleBarColor];
    self.bMenubarTextcolorNomal = [aDecoder decodeObjectForKey:kStringsXmlBaseBMenubarTextcolorNomal];
    self.bMenubarTextcolorActive = [aDecoder decodeObjectForKey:kStringsXmlBaseBMenubarTextcolorActive];
    self.menuBarLineColor = [aDecoder decodeObjectForKey:kStringsXmlBaseMenuBarLineColor];
    self.return_url = [aDecoder decodeObjectForKey:kStringsXmlBaseReturn_url];
    self.notify_url = [aDecoder decodeObjectForKey:kStringsXmlBasenotify_url];
    self.umappkey = [aDecoder decodeObjectForKey:kStringsXmlBaseUMAppkey];
    self.partner = [aDecoder decodeObjectForKey:kStringsXmlBasepartner];
    self.seller = [aDecoder decodeObjectForKey:kStringsXmlBaseseller];
    self.rsa_private = [aDecoder decodeObjectForKey:kStringsXmlBaseRSA_PRIVATE];
    self.rsa_public = [aDecoder decodeObjectForKey:kStringsXmlBaseRSA_PUBLIC];
    self.isLandscape = [aDecoder decodeObjectForKey:kStringsXmlBaseIsLandscape];
    self.wxappid = [aDecoder decodeObjectForKey:kStringsXmlBaseWX_APP_ID];
    self.wxapikey = [aDecoder decodeObjectForKey:kStringsXmlBaseWX_API_KEY];
    self.wxmchid = [aDecoder decodeObjectForKey:kStringsXmlBaseWX_MCH_ID];
    self.wxnotifyurl = [aDecoder decodeObjectForKey:kStringsXmlBaseWX_notify_url];
    self.wxreturnurl = [aDecoder decodeObjectForKey:kStringsXmlBaseWX_return_url];
    self.wxsecrect = [aDecoder decodeObjectForKey:kStringsXmlBaseWX_secrect];
    self.isUnicom = [aDecoder decodeObjectForKey:kStringsXmlBaseIsUnicom];
    self.isCloseRefresh = [aDecoder decodeObjectForKey:kStringsXmlBaseIsCloseRefres];
    self.isClosePhoneState = [aDecoder decodeObjectForKey:kStringsXmlBaseIsClosePhoneState];
    self.isCloseLoad = [aDecoder decodeObjectForKey:kStringsXmlBaseIsCloseLoad];
    self.ydbSvnversion = [aDecoder decodeObjectForKey:kStringsXmlBaseYDBsvnversion];
    self.ydbXmlversion = [aDecoder decodeObjectForKey:kStringsXmlBaseYDBxmlversion];
    self.qqappid = [aDecoder decodeObjectForKey:kStringsXmlBaseQQAPPID];
    self.iosUmengAppkey = [aDecoder decodeObjectForKey:kStringsXmlBaseiosUmengAppkey];
    self.PreloadState = [aDecoder decodeObjectForKey:kStringsXmlBasePreloadstate];
    self.PreloadPercent = [aDecoder decodeObjectForKey:kStringsXmlBasePreloadpercent];
    self.PreloadTime = [aDecoder decodeObjectForKey:kStringsXmlBasePreloadTime];
    self.RemindPercent = [aDecoder decodeObjectForKey:kStringsXmlBaseRemindPercent];
    self.RemindState = [aDecoder decodeObjectForKey:kStringsXmlBaseRemindState];
    self.RemindTime = [aDecoder decodeObjectForKey:kStringsXmlBaseRemindTime];
    self.ProgressViewColor = [aDecoder decodeObjectForKey:kStringsXmlBaseProgressViewColor];
    self.IsShowProgressView = [aDecoder decodeObjectForKey:kStringsXmlBaseIsShowProgressView];
    self.PreloadImg = [aDecoder decodeObjectForKey:kStringsXmlBasePreloadImg];
    self.RongyonAppkey = [aDecoder decodeObjectForKey:kStringsXmlBaserongyunAppkey];
    self.oldVersionWebView = [aDecoder decodeObjectForKey:kStringsXmlOldVersionWebView];
    self.versionName = [aDecoder decodeObjectForKey:kStringsXmlVersionName];
    self.UserAgentType = [aDecoder decodeObjectForKey:kStringsXmlUserAgentType];
    self.UserAgentContent = [aDecoder decodeObjectForKey:kStringsXmlUserAgentContent];
    self.WeChatJsPath = [aDecoder decodeObjectForKey:kStringsXmlWeChatJsPath];
    self.WeChatAccessUrl = [aDecoder decodeObjectForKey:kStringsXmlWeChatAccessUrl];
    self.webviewbg = [aDecoder decodeObjectForKey:kStringsXmlwebviewbg];
    self.IsCopy = [aDecoder decodeObjectForKey:kStringsXmlIsCopy];
    self.statusbarBgColor = [aDecoder decodeObjectForKey:kStringsXmlStatusbarBgColor];
    self.PigWxToken = [aDecoder decodeObjectForKey:kstringsXmlPigWxToken];
    self.CmsSystem = [aDecoder decodeObjectForKey:kstringsXmlCmsSystem];
    self.IsRefreshMenu = [aDecoder decodeObjectForKey:kstringsXmlIsRefreshMenu];
    self.TaobaoJs = [aDecoder decodeObjectForKey:kstringsXmlTaobaoJs];
    self.isBecomeActive = [aDecoder decodeObjectForKey:kstringsXmlisBecomeActive];
    self.AddJspath = [aDecoder decodeObjectForKey:kstringsXmlAddJspath];
    self.OpenBMKmap = [aDecoder decodeObjectForKey:kstringOpenBMKmap];
    self.TranslucentBackground = [aDecoder decodeObjectForKey:kstringTranslucentBackground];
    self.iOSOriginalStyle = [aDecoder decodeObjectForKey:kstringiOSOriginalStyle];
    self.HomePage = [aDecoder decodeObjectForKey:kstringHomePage];
    self.pingtai = [aDecoder decodeObjectForKey:kstringpingtai];
    self.LogoColor = [aDecoder decodeObjectForKey:kstringLogoColor];
    self.EnableCopy = [aDecoder decodeObjectForKey:kstringEnableCopy];
    self.isShowPagecontrol = [aDecoder decodeObjectForKey:kstringisShowPagecontrol];
    return self;
}

- (void)encodeWithCoder:(NSCoder *)aCoder
{
    
    [aCoder encodeObject:_notnetworkerror forKey:kStringsXmlBaseNotnetworkerror];
    [aCoder encodeObject:_layouttitle forKey:kStringsXmlBaseLayouttitle];
    [aCoder encodeObject:_appname forKey:kStringsXmlBaseAppname];
    [aCoder encodeObject:_appSecret forKey:kStringsXmlBaseAppSecret];
    [aCoder encodeObject:_ipaddress forKey:kStringsXmlBaseIpaddress];
    [aCoder encodeObject:_radiofirst forKey:kStringsXmlBaseRadiofirst];
    [aCoder encodeObject:_cancel forKey:kStringsXmlBaseCancel];
    [aCoder encodeObject:_hideTop forKey:kStringsXmlBaseHideTop];
    [aCoder encodeObject:_producescount forKey:kStringsXmlBaseProducescount];
    [aCoder encodeObject:_tabbarTextColor forKey:kStringsXmlBaseTabbarTextColor];
    [aCoder encodeObject:_isnewversion forKey:kStringsXmlBaseIsnewversion];
    [aCoder encodeObject:_submit forKey:kStringsXmlBaseSubmit];
    [aCoder encodeObject:_appKey forKey:kStringsXmlBaseAppKey];
    [aCoder encodeObject:_gTAppSecret forKey:kStringsXmlBaseGTAppSecret];
    [aCoder encodeObject:_appID forKey:kStringsXmlBaseAppID];
    [aCoder encodeObject:_corporateculture forKey:kStringsXmlBaseCorporateculture];
    [aCoder encodeObject:_buffernotice forKey:kStringsXmlBaseBuffernotice];
    [aCoder encodeObject:_twoexit forKey:kStringsXmlBaseTwoexit];
    [aCoder encodeObject:_pushmsgipaddress forKey:kStringsXmlBasePushmsgipaddress];
    [aCoder encodeObject:_laderoration forKey:kStringsXmlBaseLaderoration];
    [aCoder encodeObject:_isScan forKey:kStringsXmlBaseIsScan];
    [aCoder encodeObject:_gTAppKey forKey:kStringsXmlBaseGTAppKey];
    [aCoder encodeObject:_radiomore forKey:kStringsXmlBaseRadiomore];
    [aCoder encodeObject:_radioabout forKey:kStringsXmlBaseRadioabout];
    [aCoder encodeObject:_layoutbody forKey:kStringsXmlBaseLayoutbody];
    [aCoder encodeObject:_networkbad forKey:kStringsXmlBaseNetworkbad];
    [aCoder encodeObject:_notnetworkconnected forKey:kStringsXmlBaseNotnetworkconnected];
    [aCoder encodeObject:_phoneipaddress forKey:kStringsXmlBasePhoneipaddress];
    [aCoder encodeObject:_gTAppId forKey:kStringsXmlBaseGTAppId];
    [aCoder encodeObject:_radionews forKey:kStringsXmlBaseRadionews];
    [aCoder encodeObject:_banquaninfo forKey:kStringsXmlBaseBanquaninfo];
    [aCoder encodeObject:_radioproduce forKey:kStringsXmlBaseRadioproduce];
    [aCoder encodeObject:_newscount forKey:kStringsXmlBaseNewscount];
    [aCoder encodeObject:_serveripaddress forKey:kStringsXmlBaseServeripaddress];
    [aCoder encodeObject:_notnetworkenabled forKey:kStringsXmlBaseNotnetworkenabled];
    [aCoder encodeObject:_appsid forKey:kStringsXmlBaseAppsid];
    
    
    [aCoder encodeObject:_loaderImageType forKey:kStringsXmlBaseLoaderImageType];
    [aCoder encodeObject:_refresImageType forKey:kStringsXmlBaseRefresImageType];
    [aCoder encodeObject:_titleBarIsShow forKey:kStringsXmlBaseTitleBarIsShow];
    [aCoder encodeObject:_rightMenuIsShow forKey:kStringsXmlBaseRightMenuIsShow];
    [aCoder encodeObject:_bottomMenuBarHeight forKey:kStringsXmlBaseBottomMenuBarHeight];
    [aCoder encodeObject:_titleBarHeight forKey:kStringsXmlBaseTitleBarHeight];
    [aCoder encodeObject:_rightMenuFontColor forKey:kStringsXmlBaseRightMenuFontColor];
    [aCoder encodeObject:_frontSliderState forKey:kStringsXmlBaseFrontSliderState];
    [aCoder encodeObject:_frontSliderImageCount forKey:kStringsXmlBaseFrontSliderImageCount];
    [aCoder encodeObject:_bottomMenuBarBackColor forKey:kStringXmlBaseBottomMenuBarBackColor];
    [aCoder encodeObject:_adaptIOS7Nav forKey:kqqqaaqqqqAdaptIOS7Nav];
    [aCoder encodeObject:_gPSPostInterval forKey:kStringsXmlBaseGPSPostInterval];
    [aCoder encodeObject:_gPSGrabInterval forKey:kStringsXmlBaseGPSGrabInterval];
    [aCoder encodeObject:_gpsPostUrl forKey:kStringsXmlBaseGpsPostUrl];
    [aCoder encodeObject:_gPSIOSAppKey forKey:kStringsXmlBaseGPSIOSAppKey];
    
    [aCoder encodeObject:_titleBarColor forKey:kStringsXmlBaseTitleBarColor];
    [aCoder encodeObject:_bMenubarTextcolorNomal forKey:kStringsXmlBaseBMenubarTextcolorNomal];
    [aCoder encodeObject:_bMenubarTextcolorActive forKey:kStringsXmlBaseBMenubarTextcolorActive];
    [aCoder encodeObject:_menuBarLineColor forKey:kStringsXmlBaseMenuBarLineColor];
    [aCoder encodeObject:_return_url forKey:kStringsXmlBaseReturn_url];
    [aCoder encodeObject:_notify_url forKey:kStringsXmlBasenotify_url];
    [aCoder encodeObject:_umappkey forKey:kStringsXmlBaseUMAppkey];
    [aCoder encodeObject:_partner forKey:kStringsXmlBasepartner];
    [aCoder encodeObject:_seller forKey:kStringsXmlBaseseller];
    [aCoder encodeObject:_rsa_private forKey:kStringsXmlBaseRSA_PRIVATE];
    [aCoder encodeObject:_rsa_public forKey:kStringsXmlBaseRSA_PUBLIC];
    [aCoder encodeObject:_rsa_public forKey:kStringsXmlBaseIsLandscape];
    [aCoder encodeObject:_wxappid forKey:kStringsXmlBaseWX_APP_ID];
    [aCoder encodeObject:_wxapikey forKey:kStringsXmlBaseWX_API_KEY];
    [aCoder encodeObject:_wxmchid forKey:kStringsXmlBaseWX_MCH_ID];
    [aCoder encodeObject:_wxnotifyurl forKey:kStringsXmlBaseWX_notify_url];
    [aCoder encodeObject:_wxreturnurl forKey:kStringsXmlBaseWX_return_url];
    [aCoder encodeObject:_wxsecrect forKey:kStringsXmlBaseWX_secrect];
    [aCoder encodeObject:_isUnicom forKey:kStringsXmlBaseIsUnicom];
    [aCoder encodeObject:_isCloseLoad forKey:kStringsXmlBaseIsCloseLoad];
    [aCoder encodeObject:_isClosePhoneState forKey:kStringsXmlBaseIsClosePhoneState];
    [aCoder encodeObject:_isCloseRefresh forKey:kStringsXmlBaseIsCloseRefres];
    [aCoder encodeObject:_ydbXmlversion forKey:kStringsXmlBaseYDBxmlversion];
    [aCoder encodeObject:_ydbSvnversion forKey:kStringsXmlBaseYDBsvnversion];
    [aCoder encodeObject:_qqappid forKey:kStringsXmlBaseQQAPPID];
    [aCoder encodeObject:_iosUmengAppkey forKey:kStringsXmlBaseiosUmengAppkey];
    [aCoder encodeObject:_PreloadPercent forKey:kStringsXmlBasePreloadpercent];
    [aCoder encodeObject:_PreloadState forKey:kStringsXmlBasePreloadstate];
    [aCoder encodeObject:_PreloadTime forKey:kStringsXmlBasePreloadTime];
    [aCoder encodeObject:_RemindPercent forKey:kStringsXmlBaseRemindPercent];
    [aCoder encodeObject:_RemindState forKey:kStringsXmlBaseRemindState];
    [aCoder encodeObject:_RemindTime forKey:kStringsXmlBaseRemindTime];
    [aCoder encodeObject:_ProgressViewColor forKey:kStringsXmlBaseProgressViewColor];
    [aCoder encodeObject:_IsShowProgressView forKey:kStringsXmlBaseIsShowProgressView];
    [aCoder encodeObject:_PreloadImg forKey:kStringsXmlBasePreloadImg];
    [aCoder encodeObject:_RongyonAppkey forKey:kStringsXmlBaserongyunAppkey];
    [aCoder encodeObject:_RongyonAppkey forKey:kStringsXmlOldVersionWebView];
    [aCoder encodeObject:_versionName forKey:kStringsXmlVersionName];
    [aCoder encodeObject:_UserAgentType forKey:kStringsXmlUserAgentType];
    [aCoder encodeObject:_UserAgentContent forKey:kStringsXmlUserAgentContent];
    [aCoder encodeObject:_WeChatJsPath forKey:kStringsXmlWeChatJsPath];
    [aCoder encodeObject:_WeChatAccessUrl forKey:kStringsXmlWeChatAccessUrl];
    [aCoder encodeObject:_webviewbg forKey:kStringsXmlwebviewbg];
    [aCoder encodeObject:_IsCopy forKey:kStringsXmlIsCopy];
    [aCoder encodeObject:_statusbarBgColor forKey:kStringsXmlStatusbarBgColor];
    [aCoder encodeObject:_PigWxToken forKey:kstringsXmlPigWxToken];
    [aCoder encodeObject:_CmsSystem forKey:kstringsXmlCmsSystem];
    [aCoder encodeObject:_IsRefreshMenu forKey:kstringsXmlIsRefreshMenu];
    [aCoder encodeObject:_TaobaoJs forKey:kstringsXmlTaobaoJs];
    [aCoder encodeObject:_isBecomeActive forKey:kstringsXmlisBecomeActive];
    [aCoder encodeObject:_AddJspath forKey:kstringsXmlAddJspath];
    [aCoder encodeObject:_OpenBMKmap forKey:kstringOpenBMKmap];
    [aCoder encodeObject:_TranslucentBackground forKey:kstringTranslucentBackground];
    [aCoder encodeObject:_iOSOriginalStyle forKey:kstringiOSOriginalStyle];
    [aCoder encodeObject:_HomePage forKey:kstringHomePage];
    [aCoder encodeObject:_pingtai forKey:kstringpingtai];
    [aCoder encodeObject:_LogoColor forKey:kstringLogoColor];
    [aCoder encodeObject:_EnableCopy forKey:kstringEnableCopy];
    [aCoder encodeObject:_isShowPagecontrol forKey:kstringisShowPagecontrol];
}

- (id)copyWithZone:(NSZone *)zone
{
    StringsXmlBase *copy = [[StringsXmlBase alloc] init];
    
    if (copy) {
        
        copy.notnetworkerror = [self.notnetworkerror copyWithZone:zone];
        copy.layouttitle = [self.layouttitle copyWithZone:zone];
        copy.appname = [self.appname copyWithZone:zone];
        copy.appSecret = [self.appSecret copyWithZone:zone];
        copy.ipaddress = [self.ipaddress copyWithZone:zone];
        copy.radiofirst = [self.radiofirst copyWithZone:zone];
        copy.cancel = [self.cancel copyWithZone:zone];
        copy.hideTop = [self.hideTop copyWithZone:zone];
        copy.producescount = [self.producescount copyWithZone:zone];
        copy.tabbarTextColor = [self.tabbarTextColor copyWithZone:zone];
        copy.isnewversion = [self.isnewversion copyWithZone:zone];
        copy.submit = [self.submit copyWithZone:zone];
        copy.appKey = [self.appKey copyWithZone:zone];
        copy.gTAppSecret = [self.gTAppSecret copyWithZone:zone];
        copy.appID = [self.appID copyWithZone:zone];
        copy.corporateculture = [self.corporateculture copyWithZone:zone];
        copy.buffernotice = [self.buffernotice copyWithZone:zone];
        copy.twoexit = [self.twoexit copyWithZone:zone];
        copy.pushmsgipaddress = [self.pushmsgipaddress copyWithZone:zone];
        copy.laderoration = [self.laderoration copyWithZone:zone];
        copy.isScan = [self.isScan copyWithZone:zone];
        copy.gTAppKey = [self.gTAppKey copyWithZone:zone];
        copy.radiomore = [self.radiomore copyWithZone:zone];
        copy.radioabout = [self.radioabout copyWithZone:zone];
        copy.layoutbody = [self.layoutbody copyWithZone:zone];
        copy.networkbad = [self.networkbad copyWithZone:zone];
        copy.notnetworkconnected = [self.notnetworkconnected copyWithZone:zone];
        copy.phoneipaddress = [self.phoneipaddress copyWithZone:zone];
        copy.gTAppId = [self.gTAppId copyWithZone:zone];
        copy.radionews = [self.radionews copyWithZone:zone];
        copy.banquaninfo = [self.banquaninfo copyWithZone:zone];
        copy.radioproduce = [self.radioproduce copyWithZone:zone];
        copy.newscount = [self.newscount copyWithZone:zone];
        copy.serveripaddress = [self.serveripaddress copyWithZone:zone];
        copy.notnetworkenabled = [self.notnetworkenabled copyWithZone:zone];
        copy.appsid = [self.appsid copyWithZone:zone];
        copy.rightMenuFontColor = [self.rightMenuFontColor copyWithZone:zone];
        copy.refresImageType = [self.refresImageType copyWithZone:zone];
        copy.titleBarIsShow = [self.titleBarIsShow copyWithZone:zone];
        copy.rightMenuIsShow = [self.rightMenuIsShow copyWithZone:zone];
        copy.frontSliderState = [self.frontSliderState copyWithZone:zone];
        copy.titleBarHeight = [self.titleBarHeight copyWithZone:zone];
        copy.frontSliderImageCount = [self.frontSliderImageCount copyWithZone:zone];
        copy.bottomMenuBarHeight = [self.bottomMenuBarHeight copyWithZone:zone];
        copy.loaderImageType = [self.loaderImageType copyWithZone:zone];
        copy.bottomMenuBarBackColor = [self.bottomMenuBarBackColor copyWithZone:zone];
        copy.adaptIOS7Nav = [self.adaptIOS7Nav copyWithZone:zone];
        copy.gPSPostInterval = [self.gPSPostInterval copyWithZone:zone];
        copy.gPSGrabInterval = [self.gPSGrabInterval copyWithZone:zone];
        copy.gpsPostUrl = [self.gpsPostUrl copyWithZone:zone];
        copy.gPSIOSAppKey = [self.gPSIOSAppKey copyWithZone:zone];
        copy.titleBarColor = [self.titleBarColor copyWithZone:zone];
        copy.bMenubarTextcolorNomal = [self.bMenubarTextcolorNomal copyWithZone:zone];
        copy.bMenubarTextcolorActive = [self.bMenubarTextcolorActive copyWithZone:zone];
        copy.menuBarLineColor = [self.menuBarLineColor copyWithZone:zone];
        copy.return_url = [self.return_url copyWithZone:zone];
        copy.notify_url = [self.notify_url copyWithZone:zone];
        copy.umappkey = [self.umappkey copyWithZone:zone];
        copy.partner = [self.partner copyWithZone:zone];
        copy.seller = [self.seller copyWithZone:zone];
        copy.rsa_private = [self.rsa_private copyWithZone:zone];
        copy.rsa_public = [self.rsa_public copyWithZone:zone];
        copy.isLandscape = [self.isLandscape copyWithZone:zone];
        copy.wxappid = [self.wxappid copyWithZone:zone];
        copy.wxapikey = [self.wxapikey copyWithZone:zone];
        copy.wxmchid = [self.wxmchid copyWithZone:zone];
        copy.wxreturnurl = [self.wxreturnurl copyWithZone:zone];
        copy.wxnotifyurl = [self.wxnotifyurl copyWithZone:zone];
        copy.wxsecrect = [self.wxsecrect copyWithZone:zone];
        copy.isUnicom = [self.isUnicom copyWithZone:zone];
        copy.isCloseLoad = [self.isCloseLoad copyWithZone:zone];
        copy.isClosePhoneState = [self.isClosePhoneState copyWithZone:zone];
        copy.isCloseRefresh = [self.isCloseRefresh copyWithZone:zone];
        copy.ydbXmlversion = [self.ydbXmlversion copyWithZone:zone];
        copy.ydbSvnversion = [self.ydbSvnversion copyWithZone:zone];
        copy.qqappid = [self.qqappid copyWithZone:zone];
        copy.iosUmengAppkey = [self.iosUmengAppkey copyWithZone:zone];
        copy.PreloadTime = [self.PreloadTime copyWithZone:zone];
        copy.PreloadState = [self.PreloadState copyWithZone:zone];
        copy.PreloadPercent = [self.PreloadPercent copyWithZone:zone];
        copy.RemindTime = [self.RemindTime copyWithZone:zone];
        copy.RemindState = [self.RemindState copyWithZone:zone];
        copy.RemindPercent = [self.RemindPercent copyWithZone:zone];
        copy.IsShowProgressView = [self.IsShowProgressView copyWithZone:zone];
        copy.ProgressViewColor = [self.ProgressViewColor copyWithZone:zone];
        copy.PreloadImg = [self.PreloadImg copyWithZone:zone];
        copy.RongyonAppkey = [self.RongyonAppkey copyWithZone:zone];
        copy.oldVersionWebView = [self.oldVersionWebView copyWithZone:zone];
        copy.versionName = [self.versionName copyWithZone:zone];
        copy.UserAgentType = [self.UserAgentType copyWithZone:zone];
        copy.UserAgentContent = [self.UserAgentContent copyWithZone:zone];
        copy.WeChatAccessUrl = [self.WeChatAccessUrl copyWithZone:zone];
        copy.WeChatJsPath = [self.WeChatJsPath copyWithZone:zone];
        copy.webviewbg = [self.webviewbg copyWithZone:zone];
        copy.IsCopy = [self.IsCopy copyWithZone:zone];
        copy.statusbarBgColor = [self.statusbarBgColor copyWithZone:zone];
        copy.PigWxToken = [self.PigWxToken copyWithZone:zone];
        copy.CmsSystem = [self.CmsSystem copyWithZone:zone];
        copy.IsRefreshMenu = [self.IsRefreshMenu copyWithZone:zone];
        copy.TaobaoJs = [self.TaobaoJs copyWithZone:zone];
        copy.isBecomeActive = [self.isBecomeActive copyWithZone:zone];
        copy.AddJspath = [self.AddJspath copyWithZone:zone];
        copy.OpenBMKmap = [self.OpenBMKmap copyWithZone:zone];
        copy.TranslucentBackground = [self.TranslucentBackground copyWithZone:zone];
        copy.iOSOriginalStyle = [self.iOSOriginalStyle copyWithZone:zone];
        copy.HomePage = [self.HomePage copyWithZone:zone];
        copy.pingtai = [self.pingtai copyWithZone:zone];
        copy.LogoColor = [self.LogoColor copyWithZone:zone];
        copy.EnableCopy = [self.EnableCopy copyWithZone:zone];
        copy.isShowPagecontrol = [self.isShowPagecontrol copyWithZone:zone];
    }
    
    return copy;
}


@end
